import { 
    Trophy, 
    Zap,
    Brain,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,

} from "lucide-react";
import buildIds from "../buildGameIds";


export const brainGamesKidsIds = buildIds("brain", "kids");

export const getBrainKidsGames = (gameCompletionStatus)=> {
    const brainKidsGames = [
        {
            id: 'brain-kids-1',
            title: 'Water Story',
            description: 'Learn why water is important for brain health',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-1'] || false,
            isSpecial: true,
            path: '/student/brain/kids/water-story',
            index: 0
        },
        {
            id: 'brain-kids-2',
            title: 'Quiz on Brain Food',
            description: 'Test your knowledge of brain-healthy foods',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-2'] || false,
            isSpecial: true,
            path: '/student/brain/kids/quiz-on-brain-food',
            index: 1
        },
        {
            id: 'brain-kids-3',
            title: 'Reflex Brain Boost',
            description: 'Tap quickly for brain-boosting activities',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-3'] || false,
            isSpecial: true,
            path: '/student/brain/kids/reflex-brain-boost',
            index: 2
        },
        {
            id: 'brain-kids-4',
            title: 'Puzzle of Brain Care',
            description: 'Match brain care activities with their benefits',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-4'] || false,
            isSpecial: true,
            path: '/student/brain/kids/puzzle-of-brain-care',
            index: 3
        },
        {
            id: 'brain-kids-5',
            title: 'Breakfast Story',
            description: 'Learn why breakfast is important for brain function',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-5'] || false,
            isSpecial: true,
            path: '/student/brain/kids/breakfast-story',
            index: 4
        },
        {
            id: 'brain-kids-6',
            title: 'Poster: Brain Health',
            description: 'Create or select a brain health poster',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['brain-kids-6'] || false,
            isSpecial: true,
            path: '/student/brain/kids/poster-brain-health',
            index: 5
        },
        {
            id: 'brain-kids-7',
            title: 'Journal of Habits',
            description: 'Reflect on brain-healthy habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-7'] || false,
            isSpecial: true,
            path: '/student/brain/kids/journal-of-habits',
            index: 6
        },
        {
            id: 'brain-kids-8',
            title: 'Sports Story',
            description: 'Learn how sports benefit brain health',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-8'] || false,
            isSpecial: true,
            path: '/student/brain/kids/sports-story',
            index: 7
        },
        {
            id: 'brain-kids-9',
            title: 'Reflex Daily Habit',
            description: 'Practice identifying good daily habits',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-9'] || false,
            isSpecial: true,
            path: '/student/brain/kids/reflex-daily-habit',
            index: 8
        },
        {
            id: 'brain-kids-10',
            title: 'Badge: Brain Care Kid',
            description: 'Earn your badge for completing brain health challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['brain-kids-10'] || false,
            isSpecial: true,
            path: '/student/brain/kids/badge-brain-care-kid',
            index: 9
        },
        {
            id: 'brain-kids-11',
            title: 'Classroom Story',
            description: 'Learn how to stay focused in class',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-11'] || false,
            isSpecial: true,
            path: '/student/brain/kids/classroom-story',
            index: 10
        },
        {
            id: 'brain-kids-12',
            title: 'Quiz on Focus',
            description: 'Test your knowledge of focus techniques',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-12'] || false,
            isSpecial: true,
            path: '/student/brain/kids/quiz-on-focus',
            index: 11
        },
        {
            id: 'brain-kids-13',
            title: 'Reflex Attention',
            description: 'Practice attention-boosting actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-13'] || false,
            isSpecial: true,
            path: '/student/brain/kids/reflex-attention',
            index: 12
        },
        {
            id: 'brain-kids-14',
            title: 'Puzzle of Focus',
            description: 'Match focus concepts with their effects',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-14'] || false,
            isSpecial: true,
            path: '/student/brain/kids/puzzle-of-focus',
            index: 13
        },
        {
            id: 'brain-kids-15',
            title: 'Homework Story',
            description: 'Learn how to focus while doing homework',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-15'] || false,
            isSpecial: true,
            path: '/student/brain/kids/homework-story',
            index: 14
        },
        {
            id: 'brain-kids-16',
            title: 'Poster: Focus Matters',
            description: 'Create or select a focus poster',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['brain-kids-16'] || false,
            isSpecial: true,
            path: '/student/brain/kids/poster-focus-matters',
            index: 15
        },
        {
            id: 'brain-kids-17',
            title: 'Journal of Focus',
            description: 'Reflect on focus strategies',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-17'] || false,
            isSpecial: true,
            path: '/student/brain/kids/journal-of-focus',
            index: 16
        },
        {
            id: 'brain-kids-18',
            title: 'Game Story',
            description: 'Learn to balance games and study time',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-kids-18'] || false,
            isSpecial: true,
            path: '/student/brain/kids/game-story',
            index: 17
        },
        {
            id: 'brain-kids-19',
            title: 'Reflex Quick Attention',
            description: 'Test your quick attention reflexes',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-kids-19'] || false,
            isSpecial: true,
            path: '/student/brain/kids/reflex-quick-attention',
            index: 18
        },
        {
            id: 'brain-kids-20',
            title: 'Badge: Focus Kid',
            description: 'Earn your badge for completing focus challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['brain-kids-20'] || false,
            isSpecial: true,
            path: '/student/brain/kids/badge-focus-kid',
            index: 19
        }
    ];

    return brainKidsGames;
}