import { 
    Trophy, 
    Zap,
    Brain,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,
    BarChart4,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const brainGamesTeenIds = buildIds("brain", "teen")

export const getBrainTeenGames = (gameCompletionStatus) => {
    const brainTeenGames = [
        {
            id: 'brain-teens-1',
            title: 'Exercise Story',
            description: 'Learn how daily exercise benefits brain health',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-1'] || false,
            isSpecial: true,
            path: '/student/brain/teen/exercise-story',
            index: 0
        },
        {
            id: 'brain-teens-2',
            title: 'Quiz on Habits',
            description: 'Test your knowledge of brain-healthy habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-2'] || false,
            isSpecial: true,
            path: '/student/brain/teen/quiz-on-habits',
            index: 1
        },
        {
            id: 'brain-teens-3',
            title: 'Reflex Mind Check',
            description: 'Tap quickly for mind-boosting actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-3'] || false,
            isSpecial: true,
            path: '/student/brain/teen/reflex-mind-check',
            index: 2
        },
        {
            id: 'brain-teens-4',
            title: 'Puzzle: Brain Fuel',
            description: 'Match brain fuels with their sources or benefits',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-4'] || false,
            isSpecial: true,
            path: '/student/brain/teen/puzzle-brain-fuel',
            index: 3
        },
        {
            id: 'brain-teens-5',
            title: 'Junk Food Story',
            description: 'Learn how junk food affects brain function',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-5'] || false,
            isSpecial: true,
            path: '/student/brain/teen/junk-food-story',
            index: 4
        },
        {
            id: 'brain-teens-6',
            title: 'Debate: Brain vs Body',
            description: 'Participate in a debate on brain vs body health',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 10,
            xp: 15,
            completed: gameCompletionStatus['brain-teens-6'] || false,
            isSpecial: true,
            path: '/student/brain/teen/debate-brain-vs-body',
            index: 5
        },
        {
            id: 'brain-teens-7',
            title: 'Journal of Brain Fitness',
            description: 'Reflect on daily brain fitness habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-7'] || false,
            isSpecial: true,
            path: '/student/brain/teen/journal-of-brain-fitness',
            index: 6
        },
        {
            id: 'brain-teens-8',
            title: 'Simulation: Daily Routine',
            description: 'Choose the best daily routine for brain health',
            icon: <BarChart4 className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['brain-teens-8'] || false,
            isSpecial: true,
            path: '/student/brain/teen/simulation-daily-routine',
            index: 7
        },
        {
            id: 'brain-teens-9',
            title: 'Reflex Brain Boost',
            description: 'Tap for brain-boosting foods, avoid harmful ones',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-9'] || false,
            isSpecial: true,
            path: '/student/brain/teen/reflex-brain-boost',
            index: 8
        },
        {
            id: 'brain-teens-10',
            title: 'Badge: Brain Health Hero',
            description: 'Earn your badge for completing brain health practices',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['brain-teens-10'] || false,
            isSpecial: true,
            path: '/student/brain/teen/badge-brain-health-hero',
            index: 9
        },
        {
            id: 'brain-teens-11',
            title: 'Exam Story',
            description: 'Learn how distractions affect exam performance',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-11'] || false,
            isSpecial: true,
            path: '/student/brain/teen/exam-story',
            index: 10
        },
        {
            id: 'brain-teens-12',
            title: 'Quiz on Attention',
            description: 'Test your knowledge of attention boosters',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-12'] || false,
            isSpecial: true,
            path: '/student/brain/teen/quiz-on-attention',
            index: 11
        },
        {
            id: 'brain-teens-13',
            title: 'Reflex Concentration',
            description: 'Practice concentration-boosting actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-13'] || false,
            isSpecial: true,
            path: '/student/brain/teen/reflex-concentration',
            index: 12
        },
        {
            id: 'brain-teens-14',
            title: 'Puzzle of Distractions',
            description: 'Match environments with their effects on focus',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-14'] || false,
            isSpecial: true,
            path: '/student/brain/teen/puzzle-of-distractions',
            index: 13
        },
        {
            id: 'brain-teens-15',
            title: 'Social Media Story',
            description: 'Learn how social media affects focus',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-15'] || false,
            isSpecial: true,
            path: '/student/brain/teen/social-media-story',
            index: 14
        },
        {
            id: 'brain-teens-16',
            title: 'Debate: Multitask vs Focus',
            description: 'Debate the effectiveness of multitasking',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 10,
            xp: 15,
            completed: gameCompletionStatus['brain-teens-16'] || false,
            isSpecial: true,
            path: '/student/brain/teen/debate-multitask-vs-focus',
            index: 15
        },
        {
            id: 'brain-teens-17',
            title: 'Journal of Attention',
            description: 'Reflect on attention strategies',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['brain-teens-17'] || false,
            isSpecial: true,
            path: '/student/brain/teen/journal-of-attention',
            index: 16
        },
        {
            id: 'brain-teens-18',
            title: 'Simulation: Study Plan',
            description: 'Choose the best study environment',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['brain-teens-18'] || false,
            isSpecial: true,
            path: '/student/brain/teen/simulation-study-plan',
            index: 17
        },
        {
            id: 'brain-teens-19',
            title: 'Reflex Distraction Alert',
            description: 'Practice focus-boosting actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['brain-teens-19'] || false,
            isSpecial: true,
            path: '/student/brain/teen/reflex-distraction-alert',
            index: 18
        },
        {
            id: 'brain-teens-20',
            title: 'Badge: Focus Hero',
            description: 'Earn your badge for conquering distraction challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['brain-teens-20'] || false,
            isSpecial: true,
            path: '/student/brain/teen/badge-focus-hero',
            index: 19
        }
    ];

    return brainTeenGames;
}