import {
  Trophy, Coins, Puzzle, Zap, Leaf, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Book, Droplets, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, Recycle, Sun, Cloud, TreePine, Image, Clipboard
} from "lucide-react";

import buildIds from "../buildGameIds";

export const sustainabilityGameIdsKids = buildIds("sustainability", "kids")

export const getSustainabilityKidsGames = (gameCompletionStatus)=> {
    const sustainabilityGamesKids = [
        {
          id: "sustainability-kids-1",
          title: "Eco Sort Story",
          description: "You see trash on the ground. Do you pick it up or leave it?",
          icon: <Leaf className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-1"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/eco-sort-story",
          index: 0,
        },
        {
          id: "sustainability-kids-2",
          title: "Quiz on Recycling",
          description: "What goes in recycling? (a) Plastic bottle, (b) Banana peel, (c) Broken toy",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-2"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-recycling",
          index: 1,
        },
        {
          id: "sustainability-kids-3",
          title: "Reflex Recycle",
          description: "Tap quickly for 'Recycle' items, avoid 'Trash' items",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-3"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-recycle",
          index: 2,
        },
        {
          id: "sustainability-kids-4",
          title: "Puzzle: Sort the Waste",
          description: "Match 'Plastic Bottle → Recycle, Apple Core → Compost, Broken Toy → Trash'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-4"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-sort-waste",
          index: 3,
        },
        {
          id: "sustainability-kids-5",
          title: "Litter Story",
          description: "You finish a snack. Do you throw wrapper on ground or find a bin?",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-5"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/litter-story",
          index: 4,
        },
        {
          id: "sustainability-kids-6",
          title: "Poster: Reduce, Reuse, Recycle",
          description: "Create/select poster: '3 Rs Save Our Planet'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-6"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-3rs",
          index: 5,
        },
        {
          id: "sustainability-kids-7",
          title: "Journal of Recycling",
          description: "Write: 'One thing I recycled today was ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-7"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-recycling",
          index: 6,
        },
        {
          id: "sustainability-kids-8",
          title: "Plastic Bag Story",
          description: "Shop gives plastic bag. Do you take it or use your own bag?",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-8"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/plastic-bag-story",
          index: 7,
        },
        {
          id: "sustainability-kids-9",
          title: "Reflex Waste Choice",
          description: "Tap for 'Reusable,' avoid 'Single-use'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-9"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-waste-choice",
          index: 8,
        },
        {
          id: "sustainability-kids-10",
          title: "Badge: Eco Helper Kid",
          description: "Sort waste correctly 5 times to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-10"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-eco-helper-kid",
          index: 9,
        },
        {
          id: "sustainability-kids-11",
          title: "Lights Off Story",
          description: "You leave room. Do you turn off lights or leave them on?",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-11"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/lights-off-story",
          index: 10,
        },
        {
          id: "sustainability-kids-12",
          title: "Quiz on Saving Energy",
          description: "What saves energy? (a) Turn off TV when not watching, (b) Leave all lights on, (c) Keep AC on all day",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-12"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-saving-energy",
          index: 11,
        },
        {
          id: "sustainability-kids-13",
          title: "Reflex Energy Saver",
          description: "Tap for 'Turn Off,' avoid 'Leave On'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-13"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-energy-saver",
          index: 12,
        },
        {
          id: "sustainability-kids-14",
          title: "Puzzle: Energy Sources",
          description: "Match 'Sun → Solar Energy, Wind → Wind Energy, Coal → Dirty Energy'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-14"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-energy-sources",
          index: 13,
        },
        {
          id: "sustainability-kids-15",
          title: "Water Tap Story",
          description: "You see tap dripping. Do you tell an adult or ignore it?",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-15"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/water-tap-story",
          index: 14,
        },
        {
          id: "sustainability-kids-16",
          title: "Poster: Save Water",
          description: "Create/select poster: 'Every Drop Counts'",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-16"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-save-water",
          index: 15,
        },
        {
          id: "sustainability-kids-17",
          title: "Journal of Green Habits",
          description: "Write: 'One green habit I practice is ___'",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-17"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-green-habits",
          index: 16,
        },
        {
          id: "sustainability-kids-18",
          title: "Tree Planting Story",
          description: "School plants a tree. Do you help water it or ignore it?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-18"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/tree-planting-story",
          index: 17,
        },
        {
          id: "sustainability-kids-19",
          title: "Reflex Nature Care",
          description: "Tap for 'Protect Nature,' avoid 'Harm Nature'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-19"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-nature-care",
          index: 18,
        },
        {
          id: "sustainability-kids-20",
          title: "Badge: Planet Protector Kid",
          description: "Complete 5 eco-friendly actions to earn your badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-20"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-planet-protector-kid",
          index: 19,
        },
        {
          id: "sustainability-kids-21",
          title: "Ocean Cleanup Story",
          description: "You see plastic in the ocean. Do you help clean it or walk away?",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-21"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/ocean-cleanup-story",
          index: 20,
        },
        {
          id: "sustainability-kids-22",
          title: "Quiz on Wildlife Protection",
          description: "What helps protect animals? (a) Littering, (b) Protecting habitats, (c) Cutting trees",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-22"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-wildlife-protection",
          index: 21,
        },
        {
          id: "sustainability-kids-23",
          title: "Reflex Clean Air",
          description: "Tap for 'Clean Air' actions, avoid 'Pollution' actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-23"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-clean-air",
          index: 22,
        },
        {
          id: "sustainability-kids-24",
          title: "Puzzle: Green Transportation",
          description: "Match 'Bike → Clean, Car → Pollutes, Walk → Healthy'",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-24"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-green-transportation",
          index: 23,
        },
        {
          id: "sustainability-kids-25",
          title: "Badge: Earth Guardian",
          description: "Complete all eco-challenges to become an Earth Guardian",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-25"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-earth-guardian",
          index: 24,
        },
      ];

    return sustainabilityGamesKids;
}

