import {
  Trophy, Coins, Puzzle, Zap, Leaf, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Book, Droplets, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, Recycle, Sun, Cloud, TreePine, Image, Clipboard, Wind, Factory, Car, Bike, Home, DollarSign, BarChart2, Scale, Building, Banknote, LineChart, Briefcase, Megaphone, ClipboardCheck, ThumbsUp, Edit3, Handshake, LogOut, Speech, Bell, Siren, Mail, Link, MapPin, X, Loader2, Lightbulb, Trash2, Globe, Users, FlaskConical
} from "lucide-react";

import buildIds from "../buildGameIds";

export const sustainabilityGameIdsTeen = buildIds("sustainability", "teens")

export const getSustainabilityTeenGames = (gameCompletionStatus)=> {
    const sustainabilityGamesTeen = [
        {
          id: "sustainability-teens-1",
          title: "Climate Action Story",
          description: "You learn about climate change. How do you take action?",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-1"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/climate-action-story",
          index: 0,
        },
        {
          id: "sustainability-teens-2",
          title: "Quiz on Carbon Footprint",
          description: "What is a carbon footprint? (a) Shoe size, (b) Environmental impact, (c) Weather",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-2"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-carbon-footprint",
          index: 1,
        },
        {
          id: "sustainability-teens-3",
          title: "Reflex Eco Choice",
          description: 'Tap quickly for "Sustainable" actions, avoid "Wasteful" actions',
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-3"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-eco-choice",
          index: 2,
        },
        {
          id: "sustainability-teens-4",
          title: "Puzzle: Sustainable Solutions",
          description: "Match environmental problems with sustainable solutions",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-4"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-sustainable-solutions",
          index: 3,
        },
        {
          id: "sustainability-teens-5",
          title: "Renewable Energy Story",
          description: "Your school considers solar panels. What's your role?",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-5"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/renewable-energy-story",
          index: 4,
        },
        {
          id: "sustainability-teens-6",
          title: "Debate: Fossil Fuels vs Renewables",
          description: "Participate in a debate on energy sources",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-6"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-fossil-fuels-vs-renewables",
          index: 5,
        },
        {
          id: "sustainability-teens-7",
          title: "Journal of Green Living",
          description: "Reflect on your daily environmental impact",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-7"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-green-living",
          index: 6,
        },
        {
          id: "sustainability-teens-8",
          title: "Simulation: Eco-Friendly City",
          description: "Design a sustainable city with green solutions",
          icon: <Building className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-8"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-eco-friendly-city",
          index: 7,
        },
        {
          id: "sustainability-teens-9",
          title: "Reflex Green Habits",
          description: "Quickly identify sustainable daily habits",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-9"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-green-habits",
          index: 8,
        },
        {
          id: "sustainability-teens-10",
          title: "Badge: Climate Activist",
          description: "Earn your Climate Activist badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-10"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-climate-activist",
          index: 9,
        },
        {
          id: "sustainability-teens-11",
          title: "Waste Reduction Story",
          description: "Your school wants to reduce waste. How do you help?",
          icon: <Trash2 className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-11"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/waste-reduction-story",
          index: 10,
        },
        {
          id: "sustainability-teens-12",
          title: "Quiz on Circular Economy",
          description: "Test your knowledge on waste reduction and recycling",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-12"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-on-circular-economy",
          index: 11,
        },
        {
          id: "sustainability-teens-13",
          title: "Reflex Zero Waste",
          description: "Quickly identify zero-waste alternatives",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-13"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-zero-waste",
          index: 12,
        },
        {
          id: "sustainability-teens-14",
          title: "Puzzle: Waste Hierarchy",
          description: "Arrange waste management strategies in order of priority",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-14"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/puzzle-waste-hierarchy",
          index: 13,
        },
        {
          id: "sustainability-teens-15",
          title: "Plastic Pollution Story",
          description: "You see plastic pollution in your community. What's your response?",
          icon: <Recycle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-15"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/plastic-pollution-story",
          index: 14,
        },
        {
          id: "sustainability-teens-16",
          title: "Debate: Single-Use vs Reusable",
          description: "Debate the impact of single-use plastics",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-16"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/debate-single-use-vs-reusable",
          index: 15,
        },
        {
          id: "sustainability-teens-17",
          title: "Journal of Waste Audit",
          description: "Track and reflect on your waste generation",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-17"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/journal-of-waste-audit",
          index: 16,
        },
        {
          id: "sustainability-teens-18",
          title: "Simulation: Recycling Program",
          description: "Design and implement a school recycling program",
          icon: <ClipboardCheck className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-18"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-recycling-program",
          index: 17,
        },
        {
          id: "sustainability-teens-19",
          title: "Reflex Compost Master",
          description: "Quickly identify compostable vs non-compostable items",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-19"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-compost-master",
          index: 18,
        },
        {
          id: "sustainability-teens-20",
          title: "Badge: Zero Waste Champion",
          description: "Earn your Zero Waste Champion badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-20"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-zero-waste-champion",
          index: 19,
        },
        {
          id: "sustainability-teens-21",
          title: "Biodiversity Conservation Story",
          description: "Your community plans to build on a forest. What's your stance?",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-21"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/biodiversity-conservation-story",
          index: 20,
        },
        {
          id: "sustainability-teens-22",
          title: "Quiz on Sustainable Agriculture",
          description: "Test your knowledge on eco-friendly farming practices",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-22"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/quiz-sustainable-agriculture",
          index: 21,
        },
        {
          id: "sustainability-teens-23",
          title: "Reflex Ocean Protector",
          description: "Quickly identify actions that protect marine life",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-23"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/reflex-ocean-protector",
          index: 22,
        },
        {
          id: "sustainability-teens-24",
          title: "Simulation: Green Community Project",
          description: "Plan and execute a community sustainability initiative",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-24"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/simulation-green-community-project",
          index: 23,
        },
        {
          id: "sustainability-teens-25",
          title: "Badge: Sustainability Leader",
          description: "Master all sustainability challenges to become a leader",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-teens-25"] || false,
          isSpecial: true,
          path: "/student/sustainability/teens/badge-sustainability-leader",
          index: 24,
        },
    ];

    return sustainabilityGamesTeen;
};

