import { 
    Lock, 
    Users,
    Gamepad2,
    Heart,
    Shield,
    BookOpen,
    HandHeart,
    Camera,
    Smartphone,
    UserX,
    Eye,
    Smile,
    MessageSquare,
    Flag,
    RefreshCw,
    Award,
    Palette,
    Home,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const dcosGamesKidsIds = buildIds("dcos", "kids")

export const getDcosKidsGames = (gameCompletionStatus)=> {
    const dcosKidsGame = [
        {
            id: 'dcos-kids-1',
            title: 'Strong Password Reflex',
            description: 'Choose between weak and strong passwords',
            icon: <Lock className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['dcos-kids-1'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/strong-password-reflex',
            index: 0
        },
        {
            id: 'dcos-kids-2',
            title: 'Stranger Chat Story',
            description: 'Learn not to share personal info online',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-5 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-2'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/stranger-chat-story',
            index: 1
        },
        {
            id: 'dcos-kids-3',
            title: 'Photo Share Quiz',
            description: 'Should you post personal photos online?',
            icon: <Camera className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['dcos-kids-3'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/photo-share-quiz',
            index: 2
        },
        {
            id: 'dcos-kids-4',
            title: 'Personal Info Puzzle',
            description: 'Match items to Private or Okay to Share',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-6 min',
            coins: 3,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-4'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/personal-info-puzzle',
            index: 3
        },
        {
            id: 'dcos-kids-5',
            title: 'Game Invite Reflex',
            description: 'Accept from friends, decline from strangers',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-4 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-5'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/game-invite-reflex',
            index: 4
        },
        {
            id: 'dcos-kids-6',
            title: 'Safety Poster Task',
            description: 'Create a safety message poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-6'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/safety-poster',
            index: 5
        },
        {
            id: 'dcos-kids-7',
            title: 'Family Rules Story',
            description: 'Follow family device rules',
            icon: <Home className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-7'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/family-rules-story',
            index: 6
        },
        {
            id: 'dcos-kids-8',
            title: 'Device Sharing Quiz',
            description: 'Is it safe to share your device with strangers?',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['dcos-kids-8'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/device-sharing-quiz',
            index: 7
        },
        {
            id: 'dcos-kids-9',
            title: 'Online Friend Reflex',
            description: 'Never meet someone you only know online',
            icon: <UserX className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-9'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/online-friend-reflex',
            index: 8
        },
        {
            id: 'dcos-kids-10',
            title: 'Safe User Badge',
            description: 'Complete 5 safety habits to earn badge',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['dcos-kids-10'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/safe-user-badge',
            index: 9
        },
        {
            id: 'dcos-kids-11',
            title: 'Spot the Bully Quiz',
            description: 'Identify bullying behavior',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['dcos-kids-11'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/spot-bully-quiz',
            index: 10
        },
        {
            id: 'dcos-kids-12',
            title: 'Kind Words Reflex',
            description: 'Tap kind words, avoid rude ones',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['dcos-kids-12'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/kind-words-reflex',
            index: 11
        },
        {
            id: 'dcos-kids-13',
            title: 'Smile Story',
            description: 'Choose to be kind to others',
            icon: <Smile className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-13'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/smile-story',
            index: 12
        },
        {
            id: 'dcos-kids-14',
            title: 'Gossip Puzzle',
            description: 'Connect gossip to hurt feelings',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-6 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-14'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/gossip-puzzle',
            index: 13
        },
        {
            id: 'dcos-kids-15',
            title: 'Playground Bystander',
            description: 'Help a child being bullied',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-15'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/playground-bystander',
            index: 14
        },
        {
            id: 'dcos-kids-16',
            title: 'Cyberbully Report',
            description: 'Report mean comments to adults',
            icon: <Flag className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-16'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/cyberbully-report',
            index: 15
        },
        {
            id: 'dcos-kids-17',
            title: 'Role Swap Simulation',
            description: 'Experience how bullying feels',
            icon: <RefreshCw className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '8-10 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['dcos-kids-17'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/role-swap',
            index: 16
        },
        {
            id: 'dcos-kids-18',
            title: 'Journal of Kindness',
            description: 'Write about your kind act',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-kids-18'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/kindness-journal',
            index: 17
        },
        {
            id: 'dcos-kids-19',
            title: 'Friendship Reflex',
            description: 'Stand with your friend when needed',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-kids-19'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/friendship-reflex',
            index: 18
        },
        {
            id: 'dcos-kids-20',
            title: 'Kind Friend Badge',
            description: 'Complete 5 kindness acts to earn badge',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['dcos-kids-20'] || false,
            isSpecial: true,
            path: '/student/dcos/kids/kind-friend-badge',
            index: 19
        }
    ];

    return dcosKidsGame;
}