import { 
    Lock, 
    Users,
    Zap,
    Heart,
    Shield,
    Globe,
    Target,
    BookOpen,
    HandHeart,
    Camera,
    Smartphone,
    UserX,
    Eye,
    MessageSquare,
    Award,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const dcosGamesTeenIds = buildIds("dcos", "teen")

export const getDcosTeenGames = (gameCompletionStatus)=> {
    const dcosTeenGame = [
        {
            id: 'dcos-teen-1',
            title: 'Password Sharing Story',
            description: 'Never share your password with anyone',
            icon: <Lock className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-1'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/password-sharing-story',
            index: 0
        },
        {
            id: 'dcos-teen-2',
            title: 'Privacy Settings Quiz',
            description: 'Should profiles be public or private?',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-2'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/privacy-settings-quiz',
            index: 1
        },
        {
            id: 'dcos-teen-3',
            title: 'OTP Fraud Reflex',
            description: 'Detect and block OTP scams',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-3'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/otp-fraud-reflex',
            index: 2
        },
        {
            id: 'dcos-teen-4',
            title: 'Profile Picture Simulation',
            description: 'Choose safe profile picture - cartoon vs photo',
            icon: <Camera className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-4'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/profile-picture-simulation',
            index: 3
        },
        {
            id: 'dcos-teen-5',
            title: 'Social Media Journal',
            description: 'What info is okay to share online?',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-5'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/social-media-journal',
            index: 4
        },
        {
            id: 'dcos-teen-6',
            title: 'Data Consent Quiz',
            description: 'App permissions - what is safe to allow?',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-6'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/data-consent-quiz',
            index: 5
        },
        {
            id: 'dcos-teen-7',
            title: 'Fake Friend Story',
            description: 'Stranger claims to know your friend',
            icon: <UserX className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-7'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/fake-friend-story',
            index: 6
        },
        {
            id: 'dcos-teen-8',
            title: 'Safety Reflex',
            description: 'Detect and report scam ads',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-8'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/safety-reflex',
            index: 7
        },
        {
            id: 'dcos-teen-9',
            title: 'Debate: Online Friends',
            description: 'Is it safe to meet online friends in real life?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['dcos-teen-9'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/debate-stage-online-friends',
            index: 8
        },
        {
            id: 'dcos-teen-10',
            title: 'Online Safety Badge',
            description: 'Complete 5 teen safety acts',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['dcos-teen-10'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/online-safety-badge',
            index: 9
        },
        {
            id: 'dcos-teen-11',
            title: 'Cyberbully Reflex',
            description: 'Block and report hurtful comments',
            icon: <Shield className="w-6 h-6" />,  
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-11'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/cyberbully-reflex',
            index: 10
        },
        {
            id: 'dcos-teen-12',
            title: 'Peer Pressure Story',
            description: 'Friends want you to join trolling',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-12'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/peer-pressure-story',
            index: 11
        },
        {
            id: 'dcos-teen-13',
            title: 'Gossip Chain Simulation',
            description: 'Rumor spreads across 3 chats - stop it',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['dcos-teen-13'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/gossip-chain-simulation',
            index: 12
        },
        {
            id: 'dcos-teen-14',
            title: 'Debate: Trolling',
            description: 'Is trolling funny? Build your argument',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['dcos-teen-14'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/debate-stage-trolling',
            index: 13
        },
        {
            id: 'dcos-teen-15',
            title: 'Diversity Quiz',
            description: 'Defend friend mocked for their accent',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-15'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/diversity-quiz',
            index: 14
        },
        {
            id: 'dcos-teen-16',
            title: 'Encourage Roleplay',
            description: 'Classmate cyberbullied - encourage & report',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['dcos-teen-16'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/encourage-roleplay',
            index: 15
        },
        {
            id: 'dcos-teen-17',
            title: 'Empathy Journal',
            description: 'How would I feel if trolled?',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-17'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/empathy-journal',
            index: 16
        },
        {
            id: 'dcos-teen-18',
            title: 'Anti-Bully Reflex',
            description: 'Stand up when troll messages flash',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['dcos-teen-18'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/anti-bully-reflex',
            index: 17
        },
        {
            id: 'dcos-teen-19',
            title: 'Upstander Simulation',
            description: 'Group trolling victim - defend them',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 12,
            completed: gameCompletionStatus['dcos-teen-19'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/upstander-simulation',
            index: 18
        },
        {
            id: 'dcos-teen-20',
            title: 'Courage Badge',
            description: 'Complete 5 anti-bullying acts',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['dcos-teen-20'] || false,
            isSpecial: true,
            path: '/student/dcos/teen/courage-badge',
            index: 19
        }
    ];

    return dcosTeenGame;
}