# -*- coding: utf-8 -*-
"""chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARKtglZwUmmXH7Wa6QvBgNr1hpGG2tLx
"""

from dotenv import load_dotenv
load_dotenv()

import streamlit as st
import os
import google.generativeai as genai

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

#function to load gemini pro model

model=genai.GenerativeModel("gemini-pro")
chat=model.start_chat(history=[])


def get_gemini_response(question):
    response=chat.send_message(question,stream=True)
    return response

##initialie our streamlit app

st.set_page_config(page_title='chatbot for finmen')
st.header("gemini llm application")

#initialize session state for chat history if doesnot exaist
if 'chat_history' not in st.session_state:
    st.session_state['chat_history']=[]

input=st.text_input("input:",key='input')
submit=st.button("ask the question")

if submit and input:
    response=get_gemini_response(input)
    ## add user query and response to session chat history

    st.session_state['chat_history'].append("you",input)
    st.subheader("the response is")
    for chunk in response:
        st.write(chunk.text)
        st.session_state['chat_history'].append(('bot',chunk.text))

    st.subheader("History")

    for role,text in st.session_state['chat_history']:
        st.write(f"{role}:{text}")





















