import { 
    Trophy, 
    Users,
    Zap,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    HandHeart,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesKidsIds = buildIds("uvls", "kids")

export const getUvlsKidsGames = (gameCompletionStatus)=> {
    const uvlsGamesKid = [
        {
            id: 'uvls-kids-1',
            title: 'Share Your Toy',
            description: 'Practice simple sharing in play',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-1'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/share-your-toy',
            index: 0
        },
        {
            id: 'uvls-kids-2',
            title: 'Feelings Quiz',
            description: 'Recognize caregiving actions',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-2'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/feelings-quiz',
            index: 1
        },
        {
            id: 'uvls-kids-3',
            title: 'Kind Reflex',
            description: 'Rapidly identify kind vs mean actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2-3 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-3'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/kind-reflex',
            index: 2
        },
        {
            id: 'uvls-kids-4',
            title: 'Match Faces',
            description: 'Link facial expressions to feelings',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-4'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/match-faces',
            index: 3
        },
        {
            id: 'uvls-kids-5',
            title: 'Spot Help',
            description: 'Notice peers who need help',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-5'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/spot-help',
            index: 4
        },
        {
            id: 'uvls-kids-6',
            title: 'Kind Poster',
            description: 'Express compassion visually',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '10-12 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-kids-6'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/kind-poster',
            index: 5
        },
        {
            id: 'uvls-kids-7',
            title: 'Mini Journal',
            description: 'Put helping into words (very short)',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-7'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/mini-journal',
            index: 6
        },
        {
            id: 'uvls-kids-8',
            title: 'Comfort Roleplay',
            description: 'Choose kind phrases to comfort a sad peer',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-8'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/comfort-roleplay',
            index: 7
        },
        {
            id: 'uvls-kids-9',
            title: 'Share Reflex',
            description: 'Reinforce sharing cue recognition',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2-3 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-9'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/share-reflex',
            index: 8
        },
        {
            id: 'uvls-kids-10',
            title: 'Little Empath Badge',
            description: 'Encourage consistent small acts of empathy',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: 'Cumulative',
            coins: 3,
            xp: 20,
            completed: gameCompletionStatus['uvls-kids-10'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/little-empath-badge',
            index: 9
        },
        {
            id: 'uvls-kids-11',
            title: 'Greet the New Kid',
            description: 'Model welcoming behaviour',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-11'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/greet-the-new-kid',
            index: 10
        },
        {
            id: 'uvls-kids-12',
            title: 'Polite Words Quiz',
            description: 'Identify polite language',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-12'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/polite-words-quiz',
            index: 11
        },
        {
            id: 'uvls-kids-13',
            title: 'Respect Tap',
            description: 'Spot respectful actions quickly',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2-3 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-13'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/respect-tap',
            index: 12
        },
        {
            id: 'uvls-kids-14',
            title: 'Inclusion Match',
            description: 'Link inclusive acts to positive outcomes',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-14'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/inclusion-match',
            index: 13
        },
        {
            id: 'uvls-kids-15',
            title: 'Invite to Play',
            description: 'Practice inviting someone to join',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-15'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/invite-to-play',
            index: 14
        },
        {
            id: 'uvls-kids-16',
            title: 'Inclusion Poster',
            description: 'Visualize "everyone belongs"',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '10-12 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-kids-16'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/inclusion-poster',
            index: 15
        },
        {
            id: 'uvls-kids-17',
            title: 'Inclusion Journal',
            description: 'Reflect on an inclusion act (one line)',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-17'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/inclusion-journal',
            index: 16
        },
        {
            id: 'uvls-kids-18',
            title: 'Invite Roleplay',
            description: 'Choose inviting phrases to include shy students',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-kids-18'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/invite-roleplay',
            index: 17
        },
        {
            id: 'uvls-kids-19',
            title: 'Respect Signals',
            description: 'Recognize respect signals (eye contact, listening)',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3-4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-kids-19'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/respect-signals',
            index: 18
        },
        {
            id: 'uvls-kids-20',
            title: 'Inclusive Kid Badge',
            description: 'Reinforce repeated inclusive actions',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: 'Cumulative',
            coins: 3,
            xp: 20,
            completed: gameCompletionStatus['uvls-kids-20'] || false,
            isSpecial: true,
            path: '/student/uvls/kids/inclusive-kid-badge',
            index: 19
        }
    ];

    return uvlsGamesKid;
}
