import { 
    Trophy, 
    Users,
    Zap,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    HandHeart,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesTeenIds = buildIds("uvls", "teen")

export const getUvlsTeenGames = (gameCompletionStatus)=> {
    const uvlsGamesTeen = [
        {
            id: 'uvls-teen-1',
            title: 'Listen Deep',
            description: 'Respond supportively to a peer sharing a personal problem',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-1'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/listen-deep',
            index: 0
        },
        {
            id: 'uvls-teen-2',
            title: 'Empathy Quiz',
            description: 'Distinguish empathy vs sympathy in scenarios',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-teen-2'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/empathy-quiz',
            index: 1
        },
        {
            id: 'uvls-teen-3',
            title: 'Perspective Puzzle',
            description: 'Map responses to how they help others',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-3'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/perspective-puzzle',
            index: 2
        },
        {
            id: 'uvls-teen-4',
            title: 'Walk in Shoes Simulation',
            description: 'Experience choices as a marginalized student',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-teen-4'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/walk-in-shoes',
            index: 3
        },
        {
            id: 'uvls-teen-5',
            title: 'Empathy Debate',
            description: 'Argue for school empathy curriculum',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '20-30 min',
            coins: 5,
            xp: 20,
            completed: gameCompletionStatus['uvls-teen-5'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/empathy-debate',
            index: 4
        },
        {
            id: 'uvls-teen-6',
            title: 'Reflective Journal',
            description: 'Write reflecting on understanding someone different',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '10-12 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-6'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/reflective-journal',
            index: 5
        },
        {
            id: 'uvls-teen-7',
            title: 'Peer Support Roleplay',
            description: 'Practice a peer-support conversation',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-teen-7'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/peer-support-roleplay',
            index: 6
        },
        {
            id: 'uvls-teen-8',
            title: 'Case-Response Puzzle',
            description: 'Choose best empathetic responses in a multi-part case',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-8'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/case-response-puzzle',
            index: 7
        },
        {
            id: 'uvls-teen-9',
            title: 'Spot Distress Reflex',
            description: 'Rapidly detect subtle distress cues',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-teen-9'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/spot-distress-reflex',
            index: 8
        },
        {
            id: 'uvls-teen-10',
            title: 'Empathy Champion Badge',
            description: 'Complete 5 teen empathy tasks',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: 'Cumulative',
            coins: 3,
            xp: 20,
            completed: gameCompletionStatus['uvls-teen-10'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/empathy-champion-badge',
            index: 9
        },
        {
            id: 'uvls-teen-11',
            title: 'Cultural Greeting',
            description: 'Choose respectful greeting for different cultural contexts',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-11'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/cultural-greeting',
            index: 10
        },
        {
            id: 'uvls-teen-12',
            title: 'Inclusion Quiz',
            description: 'Identify inclusive school actions/policies',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-teen-12'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/inclusion-quiz',
            index: 11
        },
        {
            id: 'uvls-teen-13',
            title: 'Accessibility Puzzle',
            description: 'Match accommodations to student needs',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-13'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/accessibility-puzzle',
            index: 12
        },
        {
            id: 'uvls-teen-14',
            title: 'Inclusive Class Simulation',
            description: 'Design an activity that allows participation for all',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '10-12 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-teen-14'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/inclusive-class-simulation',
            index: 13
        },
        {
            id: 'uvls-teen-15',
            title: 'Respect Debate',
            description: 'Debate whether respect equals agreement',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '20 min',
            coins: 5,
            xp: 20,
            completed: gameCompletionStatus['uvls-teen-15'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/respect-debate',
            index: 14
        },
        {
            id: 'uvls-teen-16',
            title: 'Inclusion Journal',
            description: 'Describe when you challenged exclusion & outcome',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '10 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['uvls-teen-16'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/inclusion-journal',
            index: 15
        },
        {
            id: 'uvls-teen-17',
            title: 'Correcting Bias Roleplay',
            description: 'Practice calling out bias respectfully',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-teen-17'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/correcting-bias-roleplay',
            index: 16
        },
        {
            id: 'uvls-teen-18',
            title: 'Name Respect Reflex',
            description: 'Identify correct pronunciation & respond respectfully',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['uvls-teen-18'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/name-respect-reflex',
            index: 17
        },
        {
            id: 'uvls-teen-19',
            title: 'Policy Case Puzzle',
            description: 'Recommend inclusive policy actions for a school case',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['uvls-teen-19'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/policy-case-puzzle',
            index: 18
        },
        {
            id: 'uvls-teen-20',
            title: 'Respect Leader Badge',
            description: 'Complete 5 inclusion leadership tasks',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: 'Variable',
            coins: 3,
            xp: 25,
            completed: gameCompletionStatus['uvls-teen-20'] || false,
            isSpecial: true,
            path: '/student/uvls/teen/respect-leader-badge',
            index: 19
        }
    ];

    return uvlsGamesTeen;
}
