import { 
    Star,
    Zap,
    Gamepad2,
    Brain,
    Heart,
    Target,
    Cpu,
    Eye,
    Smile,
    MessageSquare,
    Palette,
    Home,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const aiGamesKidsIds = buildIds('ai', 'kids');

export const getAiKidsGames = (gameCompletionStatus)=> {
    const aiGamesKid = [
        {
            id: 'ai-kids-1',
            title: 'Spot the Pattern',
            description: 'Find what comes next in the pattern',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-1'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/spot-the-pattern',
            index: 0
        },
        {
            id: 'ai-kids-2',
            title: 'Cat or Dog Game',
            description: 'Sort images into cat or dog',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-2'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/cat-or-dog-game',
            index: 1
        },
        {
            id: 'ai-kids-3',
            title: 'Sorting Colors',
            description: 'Drag objects to correct color boxes',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-3'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/sorting-colors',
            index: 2
        },
        {
            id: 'ai-kids-4',
            title: 'True or False AI Quiz',
            description: 'AI means Artificial Intelligence?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-4'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/true-false-ai-quiz',
            index: 3
        },
        {
            id: 'ai-kids-5',
            title: 'Emoji Classifier',
            description: 'Sort emojis into happy or sad buckets',
            icon: <Smile className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-5'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/emoji-classifier',
            index: 4
        },
        {
            id: 'ai-kids-6',
            title: 'Self-Driving Car Game',
            description: 'Help AI car respond to traffic lights',
            icon: <Cpu className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-kids-6'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/self-driving-car',
            index: 5
        },
        {
            id: 'ai-kids-7',
            title: 'Pattern Finder Puzzle',
            description: 'Find missing numbers in sequences',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-7'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/pattern-finder-puzzle',
            index: 6
        },
        {
            id: 'ai-kids-8',
            title: 'Robot Helper Story',
            description: 'Learn to appreciate AI helpers',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-8'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/robot-helper-story',
            index: 7
        },
        {
            id: 'ai-kids-9',
            title: 'Spam vs Not Spam',
            description: 'Filter emails like AI does',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-9'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/spam-vs-not-spam',
            index: 8
        },
        {
            id: 'ai-kids-10',
            title: 'Siri/Alexa Quiz',
            description: 'Learn about AI assistants',
            icon: <Cpu className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-10'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/siri-alexa-quiz',
            index: 9
        },
        {
            id: 'ai-kids-11',
            title: 'AI in Games',
            description: 'Who controls video game enemies?',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-11'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/ai-in-games',
            index: 10
        },
        {
            id: 'ai-kids-12',
            title: 'Match AI Tools',
            description: 'Identify which tools use AI',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-12'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/match-ai-tools',
            index: 11
        },
        {
            id: 'ai-kids-13',
            title: 'Pattern Music Game',
            description: 'Repeat rhythm patterns',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-13'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/pattern-music-game',
            index: 12
        },
        {
            id: 'ai-kids-14',
            title: 'Robot Vision Game',
            description: 'Help robot see apple vs banana',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-14'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/robot-vision-game',
            index: 13
        },
        {
            id: 'ai-kids-15',
            title: 'Smart Home Story',
            description: 'How AI controls smart homes',
            icon: <Home className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-15'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/smart-home-story',
            index: 14
        },
        {
            id: 'ai-kids-16',
            title: 'Train the Robot',
            description: 'Teach robot what food is',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-kids-16'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/train-the-robot',
            index: 15
        },
        {
            id: 'ai-kids-17',
            title: 'Prediction Puzzle',
            description: 'Predict what comes next',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-17'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/prediction-puzzle',
            index: 16
        },
        {
            id: 'ai-kids-18',
            title: 'Friendly AI Quiz',
            description: 'Should AI help people?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-18'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/friendly-ai-quiz',
            index: 17
        },
        {
            id: 'ai-kids-19',
            title: 'Robot Emotion Story',
            description: 'Show empathy with AI',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-kids-19'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/robot-emotion-story',
            index: 18
        },
        {
            id: 'ai-kids-20',
            title: 'Recommendation Game',
            description: 'How AI recommends content',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ai-kids-20'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/kids/recommendation-game',
            index: 19
        }
    ];

    return aiGamesKid;
}
