import { 
    Star,
    Zap,
    Gamepad2,
    Brain,
    Globe,
    Target,
    Cpu,
    Smartphone,
    Eye,
    Smile,
    MessageSquare,
    Home,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const aiGamesTeenIds = buildIds('ai', 'teen');

export const getAiTeenGames = (gameCompletionStatus)=> {
    const aiGamesTeen = [
        {
            id: 'ai-teen-1',
            title: 'What is AI? Quiz',
            description: 'Define what AI stands for',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-1'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/what-is-ai-quiz',
            index: 0
        },
        {
            id: 'ai-teen-2',
            title: 'Pattern Prediction Puzzle',
            description: 'Predict the next number in sequences',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-2'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/pattern-prediction-puzzle',
            index: 1
        },
        {
            id: 'ai-teen-3',
            title: 'Image Classifier Game',
            description: 'Sort images into categories',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-3'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/image-classifier-game',
            index: 2
        },
        {
            id: 'ai-teen-4',
            title: 'Human vs AI Quiz',
            description: 'Is Google Translate powered by AI?',
            icon: <Cpu className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-4'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/human-vs-ai-quiz',
            index: 3
        },
        {
            id: 'ai-teen-5',
            title: 'Predict the Next Word',
            description: 'Complete sentences like GPT does',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-5'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/predict-next-word',
            index: 4
        },
        {
            id: 'ai-teen-6',
            title: 'Self-Driving Car Reflex',
            description: 'React fast to traffic lights',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-6'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/self-driving-car-reflex',
            index: 5
        },
        {
            id: 'ai-teen-7',
            title: 'Sorting Emotions Game',
            description: 'Classify emotions from emojis',
            icon: <Smile className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-7'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/sorting-emotions-game',
            index: 6
        },
        {
            id: 'ai-teen-8',
            title: 'True or False AI Quiz',
            description: 'Is a calculator AI?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-8'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/true-false-ai-quiz',
            index: 7
        },
        {
            id: 'ai-teen-9',
            title: 'Chatbot Simulation',
            description: 'Have a conversation with an AI bot',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-9'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/chatbot-simulation',
            index: 8
        },
        {
            id: 'ai-teen-10',
            title: 'AI in Gaming Story',
            description: 'Who controls video game enemies?',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-10'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/ai-in-gaming-story',
            index: 9
        },
        {
            id: 'ai-teen-11',
            title: 'Pattern Music Reflex',
            description: 'Repeat rhythm patterns',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-11'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/pattern-music-reflex',
            index: 10
        },
        {
            id: 'ai-teen-12',
            title: 'Computer Vision Basics',
            description: 'Identify objects with AI eyes',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-12'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/computer-vision-basics',
            index: 11
        },
        {
            id: 'ai-teen-13',
            title: 'AI in Smartphones Quiz',
            description: 'Does face unlock use AI?',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-13'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/ai-in-smartphones-quiz',
            index: 12
        },
        {
            id: 'ai-teen-14',
            title: 'Prediction Story',
            description: 'How AI forecasts weather',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-14'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/prediction-story',
            index: 13
        },
        {
            id: 'ai-teen-15',
            title: 'Machine vs Human Reflex',
            description: 'Identify Human or AI quickly',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 20,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-15'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/machine-vs-human-reflex',
            index: 14
        },
        {
            id: 'ai-teen-16',
            title: 'Language AI Quiz',
            description: 'Is Google Translate an AI?',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-16'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/language-ai-quiz',
            index: 15
        },
        {
            id: 'ai-teen-17',
            title: 'Simple Algorithm Puzzle',
            description: 'Arrange steps to solve a problem',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-17'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/simple-algorithm-puzzle',
            index: 16
        },
        {
            id: 'ai-teen-18',
            title: 'Smart Home Story',
            description: 'How AI controls smart homes',
            icon: <Home className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ai-teen-18'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/smart-home-story',
            index: 17
        },
        {
            id: 'ai-teen-19',
            title: 'Recommendation Simulation',
            description: 'How AI recommends content',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ai-teen-19'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/recommendation-simulation',
            index: 18
        },
        {
            id: 'ai-teen-20',
            title: 'AI Everywhere Quiz',
            description: 'Understand AI\'s reach in our world',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ai-teen-20'] || false,
            isSpecial: true,
            path: '/student/ai-for-all/teen/ai-everywhere-quiz',
            index: 19
        }
    ];

    return aiGamesTeen;
}
