import { 
    Trophy,
    Zap,
    Wallet,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const financegGameIdsKids = buildIds("finance", "kids")

export const getFinanceKidsGames = (gameCompletionStatus)=> {
    const financeGamesKids = [
        {
            id: 'finance-kids-1',
            title: 'Piggy Bank Story',
            description: 'You get ₹10. Do you save ₹5 or spend all?',
            icon: <Wallet className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-1'] || false,
            isSpecial: true,
            path: '/student/finance/kids/piggy-bank-story',
            index: 0
        },
        {
            id: 'finance-kids-2',
            title: 'Quiz on Saving',
            description: 'Best saver? (a) Spends all, (b) Saves part, (c) Wastes money',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-2'] || false,
            isSpecial: true,
            path: '/student/finance/kids/quiz-on-saving',
            index: 1
        },
        {
            id: 'finance-kids-3',
            title: 'Reflex Savings',
            description: 'Tap quickly for "Save" words, avoid "Waste" words',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-3'] || false,
            isSpecial: true,
            path: '/student/finance/kids/reflex-savings',
            index: 2
        },
        {
            id: 'finance-kids-4',
            title: 'Puzzle: Save or Spend',
            description: 'Match "Piggy Bank → Save, Ice Cream → Spend"',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-4'] || false,
            isSpecial: true,
            path: '/student/finance/kids/puzzle-save-or-spend',
            index: 3
        },
        {
            id: 'finance-kids-5',
            title: 'Birthday Money Story',
            description: 'You get birthday gift money. Do you save some?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-5'] || false,
            isSpecial: true,
            path: '/student/finance/kids/birthday-money-story',
            index: 4
        },
        {
            id: 'finance-kids-6',
            title: 'Poster: Saving Habit',
            description: 'Create/select poster: "Save First, Spend Later"',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['finance-kids-6'] || false,
            isSpecial: true,
            path: '/student/finance/kids/poster-saving-habit',
            index: 5
        },
        {
            id: 'finance-kids-7',
            title: 'Journal of Saving',
            description: 'Write: "One thing I saved money for is ___"',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-7'] || false,
            isSpecial: true,
            path: '/student/finance/kids/journal-of-saving',
            index: 6
        },
        {
            id: 'finance-kids-8',
            title: 'Shop Story',
            description: 'You see candy. Do you buy or save for toy later?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-8'] || false,
            isSpecial: true,
            path: '/student/finance/kids/shop-story',
            index: 7
        },
        {
            id: 'finance-kids-9',
            title: 'Reflex Money Choice',
            description: 'Tap for "Deposit," for "Throw Away"',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-9'] || false,
            isSpecial: true,
            path: '/student/finance/kids/reflex-money-choice',
            index: 8
        },
        {
            id: 'finance-kids-10',
            title: 'Badge: Saver Kid',
            description: 'Save in 5 scenarios to earn your badge',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['finance-kids-10'] || false,
            isSpecial: true,
            path: '/student/finance/kids/badge-saver-kid',
            index: 9
        },
        {
            id: 'finance-kids-11',
            title: 'Ice Cream Story',
            description: 'You have ₹10. Spend on ice cream now or save for toy?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-11'] || false,
            isSpecial: true,
            path: '/student/finance/kids/ice-cream-story',
            index: 10
        },
        {
            id: 'finance-kids-12',
            title: 'Quiz on Spending',
            description: 'Best spending habit? (a) Buy without thinking, (b) Compare and choose, (c) Borrow for fun',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-12'] || false,
            isSpecial: true,
            path: '/student/finance/kids/quiz-on-spending',
            index: 11
        },
        {
            id: 'finance-kids-13',
            title: 'Reflex Spending',
            description: 'Tap for "Plan Purchase," for "Impulse Buy"',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-13'] || false,
            isSpecial: true,
            path: '/student/finance/kids/reflex-spending',
            index: 12
        },
        {
            id: 'finance-kids-14',
            title: 'Puzzle: Smart vs Waste',
            description: 'Match "Notebook → Need, Extra Candy → Waste"',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-14'] || false,
            isSpecial: true,
            path: '/student/finance/kids/puzzle-smart-vs-waste',
            index: 13
        },
        {
            id: 'finance-kids-15',
            title: 'Shop Story 2',
            description: 'You see two pens: one costly, one affordable. Which to buy wisely?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-15'] || false,
            isSpecial: true,
            path: '/student/finance/kids/shop-story-2',
            index: 14
        },
        {
            id: 'finance-kids-16',
            title: 'Poster: Smart Shopping',
            description: 'Create/select poster: "Think Before You Spend"',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['finance-kids-16'] || false,
            isSpecial: true,
            path: '/student/finance/kids/poster-smart-shopping',
            index: 15
        },
        {
            id: 'finance-kids-17',
            title: 'Journal of Smart Buy',
            description: 'Write: "One smart thing I bought was ___"',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-17'] || false,
            isSpecial: true,
            path: '/student/finance/kids/journal-of-smart-buy',
            index: 16
        },
        {
            id: 'finance-kids-18',
            title: 'Candy Offer Story',
            description: 'Offer says "Buy 1, Get 1 Free." Do you need it?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-kids-18'] || false,
            isSpecial: true,
            path: '/student/finance/kids/candy-offer-story',
            index: 17
        },
        {
            id: 'finance-kids-19',
            title: 'Reflex Needs First',
            description: 'Tap for "Books," for "Unneeded Toys"',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-kids-19'] || false,
            isSpecial: true,
            path: '/student/finance/kids/reflex-needs-first',
            index: 18
        },
        {
            id: 'finance-kids-20',
            title: 'Badge: Smart Spender Kid',
            description: 'Make 5 wise spending decisions',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['finance-kids-20'] || false,
            isSpecial: true,
            path: '/student/finance/kids/badge-smart-spender-kid',
            index: 19
        }
    ];

    return financeGamesKids;
}
