import { 
    Trophy,
    Users,
    Zap,
    Wallet,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,
    BarChart4,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const financegGameIdsTeen = buildIds("finance", "teen")

export const getFinanceTeenGames = (gameCompletionStatus)=> {
    const financeGamesTeen =  [
        {
            id: 'finance-teens-1',
            title: 'Pocket Money Story',
            description: 'You receive pocket money. Do you save a portion or spend it all?',
            icon: <Wallet className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-1'] || false,
            isSpecial: true,
            path: '/student/finance/teen/pocket-money-story',
            index: 0
        },
        {
            id: 'finance-teens-2',
            title: 'Quiz on Savings Rate',
            description: 'What percentage of income should you save? (a) 0%, (b) 10%, (c) 20%+',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-2'] || false,
            isSpecial: true,
            path: '/student/finance/teen/quiz-on-savings-rate',
            index: 1
        },
        {
            id: 'finance-teens-3',
            title: 'Reflex Smart Saver',
            description: 'Tap quickly for "Save" words, avoid "Waste" words',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-3'] || false,
            isSpecial: true,
            path: '/student/finance/teen/reflex-smart-saver',
            index: 2
        },
        {
            id: 'finance-teens-4',
            title: 'Puzzle of Saving Goals',
            description: 'Match saving goals with timeframes',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-4'] || false,
            isSpecial: true,
            path: '/student/finance/teen/puzzle-of-saving-goals',
            index: 3
        },
        {
            id: 'finance-teens-5',
            title: 'Salary Story',
            description: 'You get your first part-time job salary. How do you manage it?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-5'] || false,
            isSpecial: true,
            path: '/student/finance/teen/salary-story',
            index: 4
        },
        {
            id: 'finance-teens-6',
            title: 'Debate: Save vs Spend',
            description: 'Participate in a debate on saving vs spending',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['finance-teens-6'] || false,
            isSpecial: true,
            path: '/student/finance/teen/debate-save-vs-spend',
            index: 5
        },
        {
            id: 'finance-teens-7',
            title: 'Journal of Saving Goal',
            description: 'Write about your personal saving goals',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-7'] || false,
            isSpecial: true,
            path: '/student/finance/teen/journal-of-saving-goal',
            index: 6
        },
        {
            id: 'finance-teens-8',
            title: 'Simulation: Monthly Money',
            description: 'Manage a monthly budget with income and expenses',
            icon: <BarChart4 className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['finance-teens-8'] || false,
            isSpecial: true,
            path: '/student/finance/teen/simulation-monthly-money',
            index: 7
        },
        {
            id: 'finance-teens-9',
            title: 'Reflex: Wise Use',
            description: 'Tap for wise financial decisions, avoid impulsive choices',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-9'] || false,
            isSpecial: true,
            path: '/student/finance/teen/reflex-wise-use',
            index: 8
        },
        {
            id: 'finance-teens-10',
            title: 'Badge: Smart Saver',
            description: 'Earn your badge for completing saving challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['finance-teens-10'] || false,
            isSpecial: true,
            path: '/student/finance/teen/badge-smart-saver',
            index: 9
        },
        {
            id: 'finance-teens-11',
            title: 'Allowance Story',
            description: 'You receive weekly allowance. How do you allocate it?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-11'] || false,
            isSpecial: true,
            path: '/student/finance/teen/allowance-story',
            index: 10
        },
        {
            id: 'finance-teens-12',
            title: 'Spending Quiz',
            description: 'Test your knowledge on smart spending habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-12'] || false,
            isSpecial: true,
            path: '/student/finance/teen/spending-quiz',
            index: 11
        },
        {
            id: 'finance-teens-13',
            title: 'Reflex: Wise Choices',
            description: 'Make quick decisions between needs and wants',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-13'] || false,
            isSpecial: true,
            path: '/student/finance/teen/reflex-wise-choices',
            index: 12
        },
        {
            id: 'finance-teens-14',
            title: 'Puzzle: Smart Spending',
            description: 'Match spending concepts with their definitions',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-14'] || false,
            isSpecial: true,
            path: '/student/finance/teen/puzzle-smart-spending',
            index: 13
        },
        {
            id: 'finance-teens-15',
            title: 'Party Story',
            description: 'Plan a party within budget constraints',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-15'] || false,
            isSpecial: true,
            path: '/student/finance/teen/party-story',
            index: 14
        },
        {
            id: 'finance-teens-16',
            title: 'Debate: Needs vs Wants',
            description: 'Debate the difference between needs and wants',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7 min',
            coins: 0,
            xp: 15,
            completed: gameCompletionStatus['finance-teens-16'] || false,
            isSpecial: true,
            path: '/student/finance/teen/debate-needs-vs-wants',
            index: 15
        },
        {
            id: 'finance-teens-17',
            title: 'Journal of Spending',
            description: 'Reflect on your spending habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['finance-teens-17'] || false,
            isSpecial: true,
            path: '/student/finance/teen/journal-of-spending',
            index: 16
        },
        {
            id: 'finance-teens-18',
            title: 'Simulation: Shopping Mall',
            description: 'Make purchasing decisions in a shopping mall simulation',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['finance-teens-18'] || false,
            isSpecial: true,
            path: '/student/finance/teen/simulation-shopping-mall',
            index: 17
        },
        {
            id: 'finance-teens-19',
            title: 'Reflex: Control',
            description: 'Practice spending control with quick decisions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['finance-teens-19'] || false,
            isSpecial: true,
            path: '/student/finance/teen/reflex-control',
            index: 18
        },
        {
            id: 'finance-teens-20',
            title: 'Badge: Smart Spender Teen',
            description: 'Earn your badge for completing all teen finance challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8 min',
            coins: 0,
            xp: 20,
            completed: gameCompletionStatus['finance-teens-20'] || false,
            isSpecial: true,
            path: '/student/finance/teen/badge-smart-spender-teen',
            index: 19
        }
    ];

    return financeGamesTeen;
}
