import { 
    Users,
    Lightbulb,
    Star,
    TrendingUp,
    Zap,
    Brain,
    Heart,
    Shield,
    Target,
    BookOpen,
    Award,
    Palette,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGamesKidsIds = buildIds("ehe", "kids")

export const getEheKidsGames = (gameCompletionStatus)=> {
    const eheKidsGame = [
        {
            id: 'ehe-kids-1',
            title: 'Doctor Story',
            description: 'Learn about doctor\'s job',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-1'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/doctor-story',
            index: 0
        },
        {
            id: 'ehe-kids-2',
            title: 'Quiz on Jobs',
            description: 'Match people to their jobs',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 12,
            completed: gameCompletionStatus['ehe-kids-2'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-jobs',
            index: 1
        },
        {
            id: 'ehe-kids-3',
            title: 'Reflex Job Match',
            description: 'Quick matching of jobs to workplaces',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-3'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-job-match',
            index: 2
        },
        {
            id: 'ehe-kids-4',
            title: 'Puzzle: Who Does What?',
            description: 'Match jobs to their tasks',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-kids-4'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-who-does-what',
            index: 3
        },
        {
            id: 'ehe-kids-5',
            title: 'Dream Job Story',
            description: 'Find the job that fits your passion',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-5'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/dream-job-story',
            index: 4
        },
        {
            id: 'ehe-kids-6',
            title: 'Poster: My Dream Job',
            description: 'Create your dream job poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-kids-6'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-my-dream-job',
            index: 5
        },
        {
            id: 'ehe-kids-7',
            title: 'Journal of Jobs',
            description: 'Write about your future career',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-kids-7'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-jobs',
            index: 6
        },
        {
            id: 'ehe-kids-8',
            title: 'School Helper Story',
            description: 'Who keeps school safe?',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-8'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/school-helper-story',
            index: 7
        },
        {
            id: 'ehe-kids-9',
            title: 'Reflex Career Check',
            description: 'Quick career facts check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-9'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-check',
            index: 8
        },
        {
            id: 'ehe-kids-10',
            title: 'Badge: Career Explorer Kid',
            description: 'Complete career exploration',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-kids-10'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-career-explorer',
            index: 9
        },
        {
            id: 'ehe-kids-11',
            title: 'Idea Story',
            description: 'Start your lemonade business',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-11'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/idea-story',
            index: 10
        },
        {
            id: 'ehe-kids-12',
            title: 'Quiz on Skills',
            description: 'What skills help entrepreneurs?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-12'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-skills',
            index: 11
        },
        {
            id: 'ehe-kids-13',
            title: 'Reflex Skill Check',
            description: 'Identify good entrepreneur skills',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-13'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-skill-check',
            index: 12
        },
        {
            id: 'ehe-kids-14',
            title: 'Puzzle: Match Skills',
            description: 'Match roles to their actions',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-kids-14'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-skills',
            index: 13
        },
        {
            id: 'ehe-kids-15',
            title: 'Teamwork Story',
            description: 'Learn the power of collaboration',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-15'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/teamwork-story',
            index: 14
        },
        {
            id: 'ehe-kids-16',
            title: 'Poster: Skills for Success',
            description: 'Create success formula poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-kids-16'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-skills-for-success',
            index: 15
        },
        {
            id: 'ehe-kids-17',
            title: 'Journal of Skills',
            description: 'Reflect on skills to improve',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-kids-17'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-skills',
            index: 16
        },
        {
            id: 'ehe-kids-18',
            title: 'Risk Story',
            description: 'Build courage by trying new things',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-18'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/risk-story',
            index: 17
        },
        {
            id: 'ehe-kids-19',
            title: 'Reflex Innovation',
            description: 'Identify innovation mindset',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-19'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-innovation',
            index: 18
        },
        {
            id: 'ehe-kids-20',
            title: 'Badge: Young Innovator',
            description: 'Master entrepreneur skills',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-kids-20'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-young-innovator',
            index: 19
        }
    ];

    return eheKidsGame;
}