import { 
    Users,
    Lightbulb,
    Star,
    TrendingUp,
    Zap,
    Brain,
    Heart,
    Target,
    BookOpen,
    MessageSquare,
    Award,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGamesTeenIds = buildIds("ehe", "teen")

export const getEheTeenGames = (gameCompletionStatus)=> {
    const eheTeenGame = [
        {
            id: 'ehe-teen-1',
            title: 'Career Story',
            description: 'Match passion to career path',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-1'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/career-story',
            index: 0
        },
        {
            id: 'ehe-teen-2',
            title: 'Quiz on Careers',
            description: 'Test your career knowledge',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 12,
            completed: gameCompletionStatus['ehe-teen-2'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/quiz-on-careers',
            index: 1
        },
        {
            id: 'ehe-teen-3',
            title: 'Reflex Teen Career',
            description: 'Quick career matching',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-3'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/reflex-teen-career',
            index: 2
        },
        {
            id: 'ehe-teen-4',
            title: 'Puzzle: Career Match',
            description: 'Match careers to responsibilities',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-4'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/puzzle-career-match',
            index: 3
        },
        {
            id: 'ehe-teen-5',
            title: 'Passion Story',
            description: 'Find career that matches passion',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-5'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/passion-story',
            index: 4
        },
        {
            id: 'ehe-teen-6',
            title: 'Debate: One Career or Many?',
            description: 'Discuss career exploration',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-6'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/debate-one-career-or-many',
            index: 5
        },
        {
            id: 'ehe-teen-7',
            title: 'Journal of Career Choice',
            description: 'Write about career interests',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-teen-7'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/journal-of-career-choice',
            index: 6
        },
        {
            id: 'ehe-teen-8',
            title: 'Simulation: Career Fair',
            description: 'Practice professional networking',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-8'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/simulation-career-fair',
            index: 7
        },
        {
            id: 'ehe-teen-9',
            title: 'Reflex Future Check',
            description: 'Quick career facts verification',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-9'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/reflex-future-check',
            index: 8
        },
        {
            id: 'ehe-teen-10',
            title: 'Badge: Career Aware Teen',
            description: 'Career exploration achievement',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-10'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/badge-career-aware-teen',
            index: 9
        },
        {
            id: 'ehe-teen-11',
            title: 'Opportunity Story',
            description: 'Spot business opportunities',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-teen-11'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/opportunity-story',
            index: 10
        },
        {
            id: 'ehe-teen-12',
            title: 'Quiz on Entrepreneur Traits',
            description: 'Key success traits',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-12'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/quiz-on-entrepreneur-traits',
            index: 11
        },
        {
            id: 'ehe-teen-13',
            title: 'Reflex Teen Skills',
            description: 'Identify entrepreneur traits',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-13'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/reflex-teen-skills',
            index: 12
        },
        {
            id: 'ehe-teen-14',
            title: 'Puzzle: Match Traits',
            description: 'Match entrepreneur traits to actions',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-14'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/puzzle-match-traits',
            index: 13
        },
        {
            id: 'ehe-teen-15',
            title: 'Failure Story',
            description: 'Learn resilience from failure',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-teen-15'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/failure-story',
            index: 14
        },
        {
            id: 'ehe-teen-16',
            title: 'Debate: Born or Made?',
            description: 'Are entrepreneurs born or made?',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '8-10 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-16'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/debate-born-or-made',
            index: 15
        },
        {
            id: 'ehe-teen-17',
            title: 'Journal of Strengths',
            description: 'Reflect on entrepreneur strengths',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['ehe-teen-17'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/journal-of-strengths',
            index: 16
        },
        {
            id: 'ehe-teen-18',
            title: 'Simulation: Team Project',
            description: 'Resolve team conflicts',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-18'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/simulation-team-project',
            index: 17
        },
        {
            id: 'ehe-teen-19',
            title: 'Reflex Teen Innovator',
            description: 'Identify innovation behaviors',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-19'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/reflex-teen-innovator',
            index: 18
        },
        {
            id: 'ehe-teen-20',
            title: 'Badge: Future Entrepreneur',
            description: 'Master entrepreneur skills',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['ehe-teen-20'] || false,
            isSpecial: true,
            path: '/student/ehe/teen/badge-future-entrepreneur',
            index: 19
        }
    ];

    return eheTeenGame;
}