import { 
    Users,
    Zap,
    Shield,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,
    MessageSquare,
    Award,
    Palette,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const moralGamesKidsIds = buildIds("moral", "kids")

export const getMoralKidsGames = (gameCompletionStatus)=> {
    const moralGamesKid = [
        {
            id: 'moral-kids-1',
            title: 'Lost Pencil Story',
            description: 'Return what you find',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-1'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/lost-pencil-story',
            index: 0
        },
        {
            id: 'moral-kids-2',
            title: 'Homework Quiz',
            description: 'Lying about homework - is it honest?',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['moral-kids-2'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/homework-quiz',
            index: 1
        },
        {
            id: 'moral-kids-3',
            title: 'Truth Reflex',
            description: 'Tap truth or lie words',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-4 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-3'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/truth-reflex',
            index: 2
        },
        {
            id: 'moral-kids-4',
            title: 'Puzzle of Trust',
            description: 'Match Truth to Trust, Lie to Trouble',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-6 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-4'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/puzzle-of-trust',
            index: 3
        },
        {
            id: 'moral-kids-5',
            title: 'Cheating Story',
            description: 'Friend wants you to cheat',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-5'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/cheating-story',
            index: 4
        },
        {
            id: 'moral-kids-6',
            title: 'Poster of Honesty',
            description: 'Create honesty is best poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-6'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/poster-of-honesty',
            index: 5
        },
        {
            id: 'moral-kids-7',
            title: 'Journal of Truth',
            description: 'Write about telling the truth',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-7'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/journal-of-truth',
            index: 6
        },
        {
            id: 'moral-kids-8',
            title: 'Candy Shop Story',
            description: 'Return extra candy to shopkeeper',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-8'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/candy-shop-story',
            index: 7
        },
        {
            id: 'moral-kids-9',
            title: 'Reflex Quick Choice',
            description: 'Fast truth or lie tapping',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-4 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-9'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/reflex-quick-choice',
            index: 8
        },
        {
            id: 'moral-kids-10',
            title: 'Badge: Truthful Kid',
            description: 'Complete 5 honesty acts',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-kids-10'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/badge-truthful-kid',
            index: 9
        },
        {
            id: 'moral-kids-11',
            title: 'Respect Elders Story',
            description: 'Help grandpa right away',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-11'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/respect-elders-story',
            index: 10
        },
        {
            id: 'moral-kids-12',
            title: 'Polite Words Quiz',
            description: 'Identify polite language',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 8,
            completed: gameCompletionStatus['moral-kids-12'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/polite-words-quiz',
            index: 11
        },
        {
            id: 'moral-kids-13',
            title: 'Reflex Respect',
            description: 'Tap kind or rude words',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-4 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-13'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/reflex-respect',
            index: 12
        },
        {
            id: 'moral-kids-14',
            title: 'Puzzle: Respect Match',
            description: 'Listen = Respect, Mock = Hurt',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-6 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-14'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/puzzle-respect-match',
            index: 13
        },
        {
            id: 'moral-kids-15',
            title: 'Teacher Greeting Story',
            description: 'Greet teacher when they enter',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-15'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/teacher-greeting-story',
            index: 14
        },
        {
            id: 'moral-kids-16',
            title: 'Gratitude Poster',
            description: 'Create a thank you poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-16'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/gratitude-poster',
            index: 15
        },
        {
            id: 'moral-kids-17',
            title: 'Journal of Gratitude',
            description: 'Today I thanked ___ for ___',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-17'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/journal-of-gratitude',
            index: 16
        },
        {
            id: 'moral-kids-18',
            title: 'Playground Respect Story',
            description: 'Include smaller child in game',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-kids-18'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/playground-respect-story',
            index: 17
        },
        {
            id: 'moral-kids-19',
            title: 'Reflex Help',
            description: 'Tap help when needed',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3-5 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-kids-19'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/reflex-help',
            index: 18
        },
        {
            id: 'moral-kids-20',
            title: 'Badge: Respect Kid',
            description: 'Complete 5 respect actions',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-kids-20'] || false,
            isSpecial: true,
            path: '/student/moral-values/kids/badge-respect-kid',
            index: 19
        }
    ];

    return moralGamesKid;
}
