import { 
    Coins, 
    Users,
    Zap,
    Heart,
    Shield,
    Target,
    BookOpen,
    GraduationCap,
    Eye,
    MessageSquare,
    Award,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const moralGamesTeenIds = buildIds("moral", "teen")

export const getMoralTeenGames = (gameCompletionStatus)=> {
    const moralGamesTeen = [
        {
            id: 'moral-teen-1',
            title: "Friend's Lie Story",
            description: 'Refuse to lie for friend',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-1'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/friend-lie-story',
            index: 0
        },
        {
            id: 'moral-teen-2',
            title: 'White Lie Quiz',
            description: 'Can small lies be harmless?',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-teen-2'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/white-lie-quiz',
            index: 1
        },
        {
            id: 'moral-teen-3',
            title: 'Reflex: Spot Fake',
            description: 'Identify fake news quickly',
            icon: <Eye className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-teen-3'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/reflex-spot-fake',
            index: 2
        },
        {
            id: 'moral-teen-4',
            title: 'Puzzle of Integrity',
            description: 'Integrity = Doing right when unseen',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-4'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/puzzle-of-integrity',
            index: 3
        },
        {
            id: 'moral-teen-5',
            title: 'Bribe Simulation',
            description: 'Refuse bribe and report it',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '7-9 min',
            coins: 5,
            xp: 15,
            completed: gameCompletionStatus['moral-teen-5'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/bribe-simulation',
            index: 4
        },
        {
            id: 'moral-teen-6',
            title: 'Debate: Lying for Friend',
            description: 'Is lying okay to protect a friend?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['moral-teen-6'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/debate-lying-for-friend',
            index: 5
        },
        {
            id: 'moral-teen-7',
            title: 'Integrity Journal',
            description: 'Write about telling a hard truth',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-7'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/integrity-journal',
            index: 6
        },
        {
            id: 'moral-teen-8',
            title: 'Exam Cheating Story',
            description: 'Resist temptation to cheat',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-8'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/exam-cheating-story',
            index: 7
        },
        {
            id: 'moral-teen-9',
            title: 'Roleplay: Truthful Leader',
            description: 'Lead group with honesty',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-teen-9'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/roleplay-truthful-leader',
            index: 8
        },
        {
            id: 'moral-teen-10',
            title: 'Badge: Integrity Hero',
            description: 'Complete 5 integrity dilemmas',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-teen-10'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/badge-integrity-hero',
            index: 9
        },
        {
            id: 'moral-teen-11',
            title: 'Debate: Obey or Question',
            description: 'Respect vs blind obedience',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['moral-teen-11'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/debate-obey-or-question',
            index: 10
        },
        {
            id: 'moral-teen-12',
            title: 'Gratitude Story',
            description: 'Thank friend for sharing notes',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-12'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/gratitude-story',
            index: 11
        },
        {
            id: 'moral-teen-13',
            title: 'Reflex: Politeness',
            description: 'Tap polite vs rude phrases',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-teen-13'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/reflex-politeness',
            index: 12
        },
        {
            id: 'moral-teen-14',
            title: 'Puzzle of Gratitude',
            description: 'Thanks → Smile, Ignore → Hurt',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-14'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/puzzle-of-gratitude',
            index: 13
        },
        {
            id: 'moral-teen-15',
            title: 'Service Story',
            description: 'Return dropped money to conductor',
            icon: <Coins className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-15'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/service-story',
            index: 14
        },
        {
            id: 'moral-teen-16',
            title: 'Respect Journal',
            description: 'This week I showed respect by...',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['moral-teen-16'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/respect-journal',
            index: 15
        },
        {
            id: 'moral-teen-17',
            title: 'Debate: Respect Teachers',
            description: 'Argue rudely with teachers?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['moral-teen-17'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/debate-respect-teachers',
            index: 16
        },
        {
            id: 'moral-teen-18',
            title: 'Roleplay: Respect Leader',
            description: 'Lead by listening to everyone',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-teen-18'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/roleplay-respect-leader',
            index: 17
        },
        {
            id: 'moral-teen-19',
            title: 'Reflex: Gratitude',
            description: 'Spot thank you vs rude emojis',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['moral-teen-19'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/reflex-gratitude',
            index: 18
        },
        {
            id: 'moral-teen-20',
            title: 'Badge: Gratitude Hero',
            description: 'Complete 5 gratitude acts',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['moral-teen-20'] || false,
            isSpecial: true,
            path: '/student/moral-values/teen/badge-gratitude-hero',
            index: 19
        }
    ];

    return moralGamesTeen;
}
