import { 
    Trophy, 
    Users,
    Zap,
    Brain,
    Heart,
    Shield,
    Target,
    BookOpen,
    Smile,
    Award,
    Palette,
    Book,
    Hand,
    CircleQuestionMark,
    Pencil,
    ClipboardList,
    List,
    Sparkles
} from "lucide-react";
import buildIds from "../buildGameIds";


export const civicGamesKidsIds = buildIds("crgc", "kids");

export const getCivicKidsGames = (gameCompletionStatus)=> {
    const civicKidsGame = [
        {
            id: 'crgc-kids-1',
            title: "Friend's Sad Story",
            description: 'Comfort a friend in need',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-1'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/friends-sad-story',
            index: 0
        },
        {
            id: 'crgc-kids-2',
            title: 'Quiz on Empathy',
            description: 'What does empathy mean?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-2'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-empathy',
            index: 1
        },
        {
            id: 'crgc-kids-3',
            title: 'Reflex Kindness',
            description: 'Identify kind actions quickly',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-3'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-kindness',
            index: 2
        },
        {
            id: 'crgc-kids-4',
            title: 'Kindness in Action',
            description: 'Practice kindness in real life',
            icon: <Hand className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-4'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-in-action',
            index: 3
        },
        {
            id: 'crgc-kids-5',
            title: 'Empathy in Stories',
            description: 'Find empathy in stories',
            icon: <Book className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-5'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-in-stories',
            index: 4
        },
        {
            id: 'crgc-kids-6',
            title: 'Kindness Challenge',
            description: 'Complete kindness challenges',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-6'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-challenge',
            index: 5
        },
        {
            id: 'crgc-kids-7',
            title: 'Empathy Quiz',
            description: 'Test your empathy skills',
            icon: <CircleQuestionMark className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-7'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-quiz',
            index: 6
        },
        {
            id: 'crgc-kids-8',
            title: 'Kindness Stories',
            description: 'Read stories about kindness',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-8'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-stories',
            index: 7
        },
        {
            id: 'crgc-kids-9',
            title: 'Empathy Role Play',
            description: 'Practice empathy in role play',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-9'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-role-play',
            index: 8
        },
        {
            id: 'crgc-kids-10',
            title: 'Kindness Journal',
            description: 'Write about kindness',
            icon: <Pencil className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-10'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-journal',
            index: 9
        },
        {
            id: 'crgc-kids-11',
            title: 'Empathy Scenarios',
            description: 'Identify empathy in scenarios',
            icon: <ClipboardList className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-11'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-scenarios',
            index: 10
        },
        {
            id: 'crgc-kids-12',
            title: 'Kindness Actions',
            description: 'List kind actions',
            icon: <List className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-12'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-actions',
            index: 11
        },
        {
            id: 'crgc-kids-13',
            title: 'Empathy Stories',
            description: 'Write empathy stories',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-13'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-stories',
            index: 12
        },
        {
            id: 'crgc-kids-14',
            title: 'Kindness Reflection',
            description: 'Reflect on kindness',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-14'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-reflection',
            index: 13
        },
        {
            id: 'crgc-kids-15',
            title: 'Empathy Role Play',
            description: 'Practice empathy in role play',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-15'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-role-play',
            index: 14
        },
        {
            id: 'crgc-kids-16',
            title: 'Kindness Journal',
            description: 'Write about kindness',
            icon: <Pencil className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-16'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-journal',
            index: 15
        },
        {
            id: 'crgc-kids-17',
            title: 'Empathy Scenarios',
            description: 'Identify empathy in scenarios',
            icon: <ClipboardList className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-17'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-scenarios',
            index: 16
        },
        {
            id: 'crgc-kids-18',
            title: 'Kindness Actions',
            description: 'List kind actions',
            icon: <List className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-18'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/kindness-actions',
            index: 17
        },
        {
            id: 'crgc-kids-19',
            title: 'Empathy Stories',
            description: 'Write empathy stories',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-19'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/empathy-stories',
            index: 18
        },
        {
            id: 'crgc-kids-20',
            title: 'Kindness Reflection',
            description: 'Reflect on kindness',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-20'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-kindness',
            index: 19
        },
        {
            id: 'crgc-kids-21',
            title: 'Puzzle: Match Feelings',
            description: 'Match emotions to expressions',
            icon: <Smile className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-kids-21'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-feelings',
            index: 20
        },
        {
            id: 'crgc-kids-22',
            title: 'Animal Story',
            description: 'Show compassion to animals',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-22'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/animal-story',
            index: 21
        },
        {
            id: 'crgc-kids-23',
            title: 'Poster: Be Kind Always',
            description: 'Create kindness superpower poster',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-kids-23'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-be-kind-always',
            index: 22
        },
        {
            id: 'crgc-kids-24',
            title: 'Journal of Empathy',
            description: 'Write about showing kindness',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-kids-24'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-empathy',
            index: 23
        },
        {
            id: 'crgc-kids-25',
            title: 'Bully Story',
            description: 'Stand up against bullying',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-25'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/bully-story',
            index: 24
        },
        {
            id: 'crgc-kids-26',
            title: 'Reflex Help Alert',
            description: 'Choose helpful actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-26'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-help-alert',
            index: 25
        },
        {
            id: 'crgc-kids-27',
            title: 'Badge: Kind Kid',
            description: 'Master empathy skills',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-kids-27'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-kind-kid',
            index: 26
        },
        {
            id: 'crgc-kids-28',
            title: 'Classroom Story',
            description: 'Respect different languages',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-28'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/classroom-story',
            index: 27
        },
        {
            id: 'crgc-kids-29',
            title: 'Quiz on Respect',
            description: 'What does respect mean?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-29'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-respect',
            index: 28
        },
        {
            id: 'crgc-kids-30',
            title: 'Reflex Respect',
            description: 'Identify respectful actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-30'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-respect',
            index: 29
        },
        {
            id: 'crgc-kids-31',
            title: 'Puzzle: Respect Match',
            description: 'Match respect to people',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-kids-31'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-respect-match',
            index: 30
        },
        {
            id: 'crgc-kids-32',
            title: 'Gender Story',
            description: 'Everyone can play everything',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-32'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/gender-story',
            index: 31
        },
        {
            id: 'crgc-kids-33',
            title: 'Poster: Respect All',
            description: 'Every voice matters',
            icon: <Palette className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '8-10 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-kids-33'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-respect-all',
            index: 32
        },
        {
            id: 'crgc-kids-34',
            title: 'Journal of Respect',
            description: 'Write about showing respect',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-kids-34'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-respect',
            index: 33
        },
        {
            id: 'crgc-kids-35',
            title: 'Disability Story',
            description: 'Include everyone equally',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-35'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/disability-story',
            index: 34
        },
        {
            id: 'crgc-kids-36',
            title: 'Reflex Inclusion',
            description: 'Choose inclusive actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-kids-36'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-inclusion',
            index: 35
        },
        {
            id: 'crgc-kids-37',
            title: 'Badge: Respect Kid',
            description: 'Complete respect examples',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-kids-37'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-respect-kid',
            index: 36
        }
    ];

    return civicKidsGame;
}