import { 
    Puzzle,
    Users,
    Zap,
    Brain,
    Heart,
    Globe,
    BookOpen,
    MessageSquare,
    Award,
} from "lucide-react"; 
import buildIds from "../buildGameIds";

export const civicGamesTeenIds = buildIds("crgc", "teen")

export const getCivicTeenGames = (gameCompletionStatus)=> {
    const civicTeenGame = [
        {
            id: 'crgc-teen-1',
            title: 'Stranger Story',
            description: 'Help an elderly stranger',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-1'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/stranger-story',
            index: 0
        },
        {
            id: 'crgc-teen-2',
            title: 'Quiz on Compassion',
            description: 'What does compassion mean?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-2'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/quiz-on-compassion',
            index: 1
        },
        {
            id: 'crgc-teen-3',
            title: 'Reflex Teen Compassion',
            description: 'Identify compassionate actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-3'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/reflex-teen-compassion',
            index: 2
        },
        {
            id: 'crgc-teen-4',
            title: 'Puzzle: Kind Acts',
            description: 'Match compassionate actions',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-teen-4'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/puzzle-kind-acts',
            index: 3
        },
        {
            id: 'crgc-teen-5',
            title: 'Refugee Story',
            description: 'Welcome someone new',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-5'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/refugee-story',
            index: 4
        },
        {
            id: 'crgc-teen-6',
            title: 'Debate: Kindness = Weakness?',
            description: 'Argue your position',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['crgc-teen-6'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/debate-kindness-weakness',
            index: 5
        },
        {
            id: 'crgc-teen-7',
            title: 'Journal of Compassion',
            description: 'Reflect on kind acts',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-teen-7'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/journal-of-compassion',
            index: 6
        },
        {
            id: 'crgc-teen-8',
            title: 'Simulation: Hospital Visit',
            description: 'Support a sick classmate',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-8'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/simulation-hospital-visit',
            index: 7
        },
        {
            id: 'crgc-teen-9',
            title: 'Reflex Global Empathy',
            description: 'Show global compassion',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-9'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/reflex-global-empathy',
            index: 8
        },
        {
            id: 'crgc-teen-10',
            title: 'Badge: Compassion Leader',
            description: 'Complete 5 compassionate acts',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-teen-10'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/badge-compassion-leader',
            index: 9
        },
        {
            id: 'crgc-teen-11',
            title: 'Cultural Story',
            description: 'Respect different religions',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-11'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/cultural-story',
            index: 10
        },
        {
            id: 'crgc-teen-12',
            title: 'Quiz on Inclusion',
            description: 'Understanding inclusion',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-12'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/quiz-on-inclusion',
            index: 11
        },
        {
            id: 'crgc-teen-13',
            title: 'Reflex Teen Respect',
            description: 'Identify respectful actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-13'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/reflex-teen-respect',
            index: 12
        },
        {
            id: 'crgc-teen-14',
            title: 'Puzzle: Inclusion Acts',
            description: 'Match inclusive actions',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-teen-14'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/puzzle-inclusion-acts',
            index: 13
        },
        {
            id: 'crgc-teen-15',
            title: 'Religion Story',
            description: 'Respect different prayers',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-15'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/religion-story',
            index: 14
        },
        {
            id: 'crgc-teen-16',
            title: 'Debate: Equality for All?',
            description: 'Argue for equal treatment',
            icon: <MessageSquare className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '15-20 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['crgc-teen-16'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/debate-equality-for-all',
            index: 15
        },
        {
            id: 'crgc-teen-17',
            title: 'Journal of Inclusion',
            description: 'Reflect on including others',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '6-8 min',
            coins: 5,
            xp: 12,
            completed: gameCompletionStatus['crgc-teen-17'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/journal-of-inclusion',
            index: 16
        },
        {
            id: 'crgc-teen-18',
            title: 'Simulation: School Event',
            description: 'Practice inclusion',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5-7 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-18'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/simulation-school-event',
            index: 17
        },
        {
            id: 'crgc-teen-19',
            title: 'Reflex Teen Inclusion',
            description: 'Recognize inclusive actions',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4-6 min',
            coins: 3,
            xp: 10,
            completed: gameCompletionStatus['crgc-teen-19'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/reflex-teen-inclusion',
            index: 18
        },
        {
            id: 'crgc-teen-20',
            title: 'Badge: Inclusion Leader',
            description: 'Complete inclusion actions',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '2-3 min',
            coins: 3,
            xp: 15,
            completed: gameCompletionStatus['crgc-teen-20'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teen/badge-inclusion-leader',
            index: 19
        }
    ];

    return civicTeenGame;
}